intents:
  - name: flower
    utterances:
      - 꽃을 사고 싶습니다
      - 꽃을 사고 싶다
      - 꽃 내놔
      - 꽃이 필요해
      - 플라워가 필요해
      - 플라워를 사고 싶다
    confirm_prompt: '좋습니다. {pickup_date} {pickup_time}에 {kinds} 꽃을 준비해두겠습니다.'